services:
  django: &django
    build:
      context: .
    ports:
      - 8000:8000 # app port
    volumes:
      - ./media:/app/media
    environment: # all the defaults values are the ones needed by the prod environment
      DEBUG: 0 # Should be set to 0 in production !
      DJANGO_ALLOWED_HOSTS: 127.0.0.1, localhost
      DJANGO_CSRF_TRUSTED_ORIGINS: "https://paingouin.rezoleo.fr"
      ENFORCE_HTTPS: 0 # Should be set to 1 in production !
      DATABASE_ENGINE: mysql
      DATABASE_NAME: dbdjango
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: monpassword
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      EMAIL_USE_TLS: False # for mailpit
      EMAIL_USE_SSL: False # for mailpit
      EMAIL_HOST: mailpit # for mailpit
      EMAIL_PORT: 1025 # for mailpit
      EMAIL_HOST_USER: example@email.com
      EMAIL_HOST_PASSWORD: ""
      RABBITMQ_USER: paingouin
      RABBITMQ_PASS: xGmyRq8J5CSUT0fgD3m9iGgVs
      RABBITMQ_VHOST: paingouinvhost
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
      - mailpit

  celeryworker:
    <<: *django
    ports: []
    volumes: []
    entrypoint: celery -A paingouin worker --loglevel=INFO -B --concurrency=2
    depends_on:
      - rabbitmq
      - mailpit

  # brocker like redis, for celery
  rabbitmq:
    image: rabbitmq:4.1.3
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: paingouin
      RABBITMQ_DEFAULT_PASS: xGmyRq8J5CSUT0fgD3m9iGgVs
      RABBITMQ_DEFAULT_VHOST: paingouinvhost

  # For dev, creates a fake smtp server so we can see outgoing mails
  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: paingouin_local_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: mariadb:12.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  # For dev, GUI to interact directly with DB
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mariadb_data: