services:
  django: &django
    image: ghcr.io/pain-gouin/site-v4:prod
    container_name: paingouin_prod_django
    ports:
      - 8000:8000 # app server port
    volumes:
      - ./media:/app/media
    environment:
      RABBITMQ_USER: paingouin
      RABBITMQ_PASS: xGmyRq8J5CSUT0fgD3m9iGgVs
      RABBITMQ_VHOST: paingouinvhost
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
  
  celeryworker:
    <<: *django
    container_name: paingouin_prod_celeryworker
    ports: []
    volumes: []
    entrypoint: celery -A paingouin worker --loglevel=INFO -B --concurrency=2
    depends_on:
      - rabbitmq

  # brocker like redis, for celery
  rabbitmq:
    image: rabbitmq:4.1.3
    container_name: paingouin_prod_rabbitmq
    restart: always
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: paingouin
      RABBITMQ_DEFAULT_PASS: xGmyRq8J5CSUT0fgD3m9iGgVs
      RABBITMQ_DEFAULT_VHOST: paingouinvhost
