services:
  server:
    build:
      context: .
    ports:
      - 8000:8000 # app port
    volumes:
      - ./media:/app/media
    environment: # all the defaults values are the ones needed by the prod environment
      DEBUG: 0 # Should be set to 0 in production !
      DJANGO_ALLOWED_HOSTS: 127.0.0.1, localhost
      CSRF_TRUSTED_ORIGINS: "https://paingouin.rezoleo.fr"
      DATABASE_ENGINE: mysql
      DATABASE_NAME: dbdjango
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: monpassword
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
