services:
  server:
    build:
      context: .
    ports:
      - 8000:8000 # app port
      - 3306:3306 # DB port
    volumes:
      - ./media:/app/media
    environment: # all the defaults values are the ones needed by the prod environment
      DEBUG: 0 # Should be set to 0 in production !
      DJANGO_ALLOWED_HOSTS: 127.0.0.1, localhost
      DATABASE_ENGINE: mysql
      DATABASE_NAME: dbdjango
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: monpassword
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306 # doit être le même qu'indiqué plus haut !
