# Generated by Django 5.0.6 on 2024-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='zezez', max_length=500),
            preserve_default=False,
        ),
    ]
