# Generated by Django 5.0.6 on 2024-06-30 12:56

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_utilisateur_last_login_alter_utilisateur_mail'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
