# Generated by Django 5.0.6 on 2024-07-24 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_utilisateur_username_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_order',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
