# Generated by Django 5.0.6 on 2024-07-25 12:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_produit_image_produit_isquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='isQuota',
            field=models.BooleanField(default=False, verbose_name='Présence de quota pour le produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quota',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('total_commande', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.produit')),
            ],
        ),
    ]
