# Generated by Django 5.0.6 on 2024-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_alter_produit_isquota_alter_produit_quota_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='commande.produit'),
        ),
    ]
