# Generated by Django 5.0.6 on 2024-07-25 12:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0011_remove_commande_produit_commande_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('produit', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.livraison'),
        ),
    ]
