# Generated by Django 5.0.6 on 2024-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_livraison_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='produit',
            field=models.JSONField(default=dict),
        ),
    ]
