# Generated by Django 5.0.6 on 2024-07-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0013_alter_livraison_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='chambre',
            field=models.CharField(default='F222', max_length=10),
            preserve_default=False,
        ),
    ]
