# Generated by Django 5.0.6 on 2024-07-26 12:08

import commande.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0014_commande_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AlterField(
            model_name='livraison',
            name='produit',
            field=models.JSONField(default=commande.models.defaultJson),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.JSONField(default=commande.models.defaultJson),
        ),
    ]
