# Generated by Django 5.0.6 on 2024-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0015_remove_commande_produit_alter_livraison_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.CharField(max_length=100),
        ),
    ]
