# Generated by Django 5.0.6 on 2024-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0016_alter_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
