# Generated by Django 5.0.6 on 2024-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0018_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
