# Generated by Django 5.0.6 on 2024-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0019_alter_utilisateur_credit_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
