# Generated by Django 5.0.6 on 2024-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0020_alter_utilisateur_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(default=0),
        ),
    ]
