# Generated by Django 5.2.5 on 2025-08-11 14:53

import datetime
from django.db import migrations, models

# Fonction custom car certaines dates de livraisons existent en double dans la BD
def make_dates_unique(apps, schema_editor):
    # On va supprimer toutes les livraisons dont la date est en double.
    Livraison = apps.get_model("commande", "Livraison")

    # On liste toutes les dates
    for date in Livraison.objects.values_list('date', flat=True).distinct():
        # On récupère toutes les livraisons de cette date, sauf 1
        duplicates = list(Livraison.objects.filter(date=date).values_list('id', flat=True))[1:] # on doit transformer en list, pour forcer l'éxecution de la requête SQL, car sinon on a cette erreur : "This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'"
        # On les supprimes
        Livraison.objects.filter(pk__in=duplicates).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0021_produit_prix_achat'),
    ]

    operations = [
        migrations.RunPython(make_dates_unique),
        migrations.AlterField(
            model_name='livraison',
            name='date',
            field=models.DateField(default=datetime.datetime.now, unique=True),
        ),
    ]
