# Generated by Django 5.2.5 on 2025-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande", "0022_alter_livraison_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="getOrderMail",
            field=models.BooleanField(default=True),
        ),
    ]
