# Generated by Django 5.2.5 on 2025-09-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande", "0024_alter_commande_total_commande_alter_produit_prix_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="email address"
            ),
        ),
    ]
