# Generated by Django 5.2.9 on 2025-12-24 13:21

from datetime import datetime
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import connection, migrations, models
import json
from django.db.models import Sum
from django.utils import timezone


def rename_legacy_tables(apps, schema_editor):
    """
    Checks if the legacy table names exist before attempting to rename them,
    making the migration idempotent.
    """
    with connection.cursor() as cursor:
        # List of old_name: new_name pairs
        tables_to_rename = {
            "commande_utilisateur": "commande_user",
            "commande_utilisateur_groups": "commande_user_groups",
            "commande_utilisateur_user_permissions": "commande_user_user_permissions",
        }

        print()  # for beautiful output, go to line once
        for old_name, new_name in tables_to_rename.items():
            # Check if the table exists using Django's schema editor introspection
            if old_name in connection.introspection.table_names(cursor):
                print(f"Renaming table {old_name} to {new_name}...")
                cursor.execute(f"ALTER TABLE {old_name} RENAME TO {new_name};")
            else:
                print(f"Table {old_name} not found, skipping rename.")

        # --- PART 2: Rename Columns ---
        # List of tuples: (table_name, old_column_name, new_column_name)
        columns_to_rename = [
            ("commande_user_user_permissions", "utilisateur_id", "user_id"),
            ("commande_user_groups", "utilisateur_id", "user_id"),
        ]

        for table_name, old_col, new_col in columns_to_rename:
            # 1. First, ensure the table actually exists
            if table_name in connection.introspection.table_names(cursor):

                # 2. Introspect the table to get current columns
                # get_table_description returns a list of FieldInfo objects; .name holds the column name
                current_columns = [
                    col.name
                    for col in connection.introspection.get_table_description(
                        cursor, table_name
                    )
                ]

                # 3. Rename only if the old column exists
                if old_col in current_columns:
                    print(
                        f"Renaming column '{old_col}' to '{new_col}' in table '{table_name}'..."
                    )
                    # Note: RENAME COLUMN is standard SQL for Postgres/SQLite/MySQL 8.0+
                    cursor.execute(
                        f"ALTER TABLE {table_name} RENAME COLUMN {old_col} TO {new_col};"
                    )
                elif new_col in current_columns:
                    print(
                        f"Column '{new_col}' already exists in '{table_name}', skipping."
                    )
                else:
                    print(f"Column '{old_col}' not found in '{table_name}', skipping.")
            else:
                print(f"Table '{table_name}' not found, cannot rename column.")


def migrate_orders(apps, schema_editor):
    print("Migrating orders...")
    # 1. Load all historical models using apps.get_model
    # This is crucial because standard imports won't work in a migration
    OldCommande = apps.get_model("commande", "Commande")
    NewOrder = apps.get_model("commande", "Order")
    NewOrderProduct = apps.get_model("commande", "OrderProduct")

    # We also need these models to create relationships
    Transaction = apps.get_model("commande", "Transaction")
    Product = apps.get_model("commande", "Product")
    Delivery = apps.get_model("commande", "Delivery")
    User = apps.get_model(
        "commande", "User"
    )  # Replace 'commande' if User is in another app (e.g. 'auth' or 'core')

    # Iterate over every old Commande
    for old_comm in OldCommande.objects.all():

        # --- A. Retrieve the User ---
        try:
            user = User.objects.get(email=old_comm.client)
        except User.DoesNotExist:
            print(f"Skipping order {old_comm.id}: User '{old_comm.client}' not found.")
            continue

        # --- B. Retrieve or Create Delivery ---
        # Find the delivery object for that date
        delivery, created = Delivery.objects.get_or_create(date=old_comm.date)

        creation_datetime = timezone.make_aware(
            datetime.combine(old_comm.date, datetime.min.time()),
            timezone.get_default_timezone(),
        )
        # --- C. Create the New Order ---
        new_order = NewOrder.objects.create(
            client=user,
            delivery=delivery,
            room=old_comm.chambre,
            total_price_cache=old_comm.total_commande,
            created_at=creation_datetime,
        )

        # --- D. Synthesize the Payment Transaction ---
        # The new Order should have a transaction. We must recreate it from history.
        transaction = Transaction.objects.create(
            user=user,
            amount=-old_comm.total_commande,
            type="ORDER",
            order=new_order,
            initiator=user,
            created_at=creation_datetime,  # Best guess for timestamp is the delivery date
            note=f"Transaction générée automatiquement lors de la grande migration",
        )

        # --- E. Create Order Products ---
        # Handle JSON data.
        # Since old code used json.dumps(), the JSONField might contain a string representation of a list.
        raw_products = old_comm.produit
        if isinstance(raw_products, str):
            product_list = json.loads(raw_products)
        else:
            product_list = raw_products

        # product_list structure is expected to be: [[product_name, quantity], ...]
        if product_list:
            for item in product_list:
                # item[0] = Name, item[1] = Quantity
                prod_name = item[0]
                quantity = int(item[1])

                if quantity > 0:
                    try:
                        product_obj = Product.objects.get(name=prod_name)

                        NewOrderProduct.objects.create(
                            order=new_order,
                            product=product_obj,
                            quantity=quantity,
                            total_price_sold=product_obj.resell_price
                            * quantity,  # Calculate price manually (migration models don't have .save() logic)
                            total_price_bought=product_obj.purchase_price
                            * quantity,  # Calculate price manually (migration models don't have .save() logic)
                        )
                    except Product.DoesNotExist:
                        print(
                            f"Warning: Product '{prod_name}' in Commande #{old_comm.id} not found. Skipped."
                        )
    print(f"Orders migration complete.")


def migrate_credits(apps, schema_editor):
    print("Starting credit migration.")
    User = apps.get_model("commande", "User")
    Transaction = apps.get_model("commande", "Transaction")

    for user in User.objects.annotate(transaction_sum=Sum("transaction__amount")).all():
        if user.credit - (user.transaction_sum or 0) != 0:
            Transaction.objects.create(
                user=user,
                amount=user.credit - (user.transaction_sum or 0),
                type="OTHER",
                note="Transaction générée automatiquement lors de la grande migration",
                initiator=user,
                created_at=user.created_at,
            )

        user.balance_cache = (
            user.credit
        )  # Should be the case if the migration was successful
        user.save()
    print("Credit migration complete.")


def add_all_permissions(apps=None, schema_editor=None):
    from django.contrib.auth.management import create_permissions

    if apps is None:
        from django.apps import apps

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def create_default_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    DEFAULT_GROUP_NAME = "default"
    permissions = {
        "add": ["productcategory", "product", "delivery", "transaction"],
        "view": [
            "productcategory",
            "user",
            "product",
            "delivery",
            "order",
            "transaction",
            "orderproduct",
            "logentry",
        ],
        "change": ["productcategory", "user", "product"],
        "delete": ["productcategory", "user", "product", "delivery"],
    }

    default_group, created = Group.objects.get_or_create(name=DEFAULT_GROUP_NAME)
    for type in permissions:
        for model in permissions[type]:
            try:
                permission = Permission.objects.get(codename=f"{type}_{model}")
                default_group.permissions.add(permission)
            except Permission.DoesNotExist:
                print(f"ERROR: {type}_{model} permission does not exist")


def add_existing_users_to_default_group(apps, schema_editor):
    """
    Fetches all users and adds them to the 'default' group.
    """
    User = apps.get_model(
        "commande", "User"
    )  # Or your custom user app 'users', 'CustomUser'
    Group = apps.get_model("auth", "Group")

    default_group = Group.objects.get(name="default")
    users = User.objects.all()

    # Using through model for efficient bulk addition
    # This avoids calling .save() on every user
    for user in users:
        user.groups.add(default_group)


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0031_alter_utilisateur_email_verified_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=rename_legacy_tables,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RenameField(
            model_name="user",
            old_name="autorisation_verified",
            new_name="verified_genuine_user",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="chambre",
            new_name="room",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="tel",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="getOrderMail",
            new_name="get_order_email",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="isLivreur",
            new_name="is_delivery_man",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="isPermis",
            new_name="has_drivers_licence",
        ),
        migrations.AddField(
            model_name="user",
            name="balance_cache",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cache pour stocker le potentiel solde actuel de l'utilisateur. La table des transactions fait foix !",
                max_digits=8,
                verbose_name="Dernier solde calculé",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="get_order_email",
            field=models.BooleanField(
                default=True,
                help_text="Désigne si l'utilisateur souhaite recevoir des mails de confirmation de commande",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="has_drivers_licence",
            field=models.BooleanField(
                default=False,
                help_text="Désigne si l'utilisateur a le permis de conduire",
                verbose_name="Permis",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_delivery_man",
            field=models.BooleanField(
                default=False,
                help_text="Désigne si l'utilisateur a accepté de faire des livraisons",
                verbose_name="Livreur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="room",
            field=models.CharField(
                help_text="Désigne la chambre de l'utilisateur. Permet de préremplir la chambre de livraison lors d'une commande",
                max_length=10,
                null=True,
                verbose_name="Chambre",
            ),
        ),
        migrations.RenameModel(
            old_name="CategorieProduit",
            new_name="ProductCategory",
        ),
        migrations.RenameField(
            model_name="ProductCategory",
            old_name="nom",
            new_name="name",
        ),
        migrations.RenameModel(
            old_name="Produit",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="Product",
            old_name="nom",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="Product",
            old_name="prix",
            new_name="resell_price",
        ),
        migrations.RenameField(
            model_name="Product",
            old_name="prix_achat",
            new_name="purchase_price",
        ),
        migrations.RenameField(
            model_name="Product",
            old_name="categorie",
            new_name="category",
        ),
        migrations.RenameModel(
            old_name="Livraison",
            new_name="Delivery",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price_cache",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "room",
                    models.CharField(max_length=10, verbose_name="Chambre à livrer"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commande.delivery",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="delivery",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="first name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="last name"
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={"ordering": ["-date"], "verbose_name_plural": "deliveries"},
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("NA", "Rien à signaler"),
                            (
                                "NDELIV",
                                "Produit non livré, mais récupéré à la boulangerie",
                            ),
                            ("NBOUGHT", "Produit non récupéré à la boulangerie"),
                        ],
                        default="NA",
                        help_text="Permet d'identifier si le produit n'a pas été récupéré à la boulangerie, ou a été récupéré mais pas livré à l'utilisateur",
                        max_length=7,
                        verbose_name="État du produit",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="commande.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commande.product",
                    ),
                ),
                (
                    "total_price_bought",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Au moment de l'achat. Prend en compte la quantité",
                        max_digits=8,
                        verbose_name="Coût payé à la boulangerie pour l'article",
                    ),
                ),
                (
                    "total_price_sold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Au moment de l'achat. Prend en compte la quantité",
                        max_digits=8,
                        verbose_name="Coût payé par le client pour l'article",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix d'achat à la boulangerie.",
                max_digits=8,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="resell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix de revente aux centraliens sur le site.",
                max_digits=8,
                verbose_name="Prix de revente",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ORDER", "Paiement d'une commande"),
                            ("REFUND", "Remboursement d'une commande"),
                            ("LYF", "Rechargement via LYF"),
                            ("POS", "Rechargement via TPE"),
                            ("CASH", "Rechargement via Cash"),
                            ("OTHER", "Autre (à préciser !)"),
                        ],
                        max_length=6,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="Désigne la personne à l'origine de la transaction. Peut être l'utilisateur lui-même, par exemple lors d'une commande, ou bien un administrateur.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiateur de la transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="commande.order",
                        verbose_name="Commande associée",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            code=migrate_orders,
        ),
        migrations.RunPython(
            code=migrate_credits,
        ),
        migrations.DeleteModel(
            name="Commande",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="isQuota",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quota",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="user",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_order",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_price_cache",
            new_name="original_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commande.delivery",
                verbose_name="Livraison associée",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Désigne si la transaction a été annulé par l'utilisateur",
                verbose_name="Annulée",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("NA", "Rien à signaler"),
                    ("NDELIV", "Produit non livré, mais récupéré à la boulangerie"),
                    ("NBOUGHT", "Produit non récupéré à la boulangerie"),
                    ("CANCEL", "Produit annulé"),
                ],
                default="NA",
                help_text="Permet d'identifier si le produit n'a pas été récupéré à la boulangerie, ou a été récupéré mais pas livré à l'utilisateur",
                max_length=7,
                verbose_name="État de livraison du produit",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commande.order",
                verbose_name="Commande associée",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commande.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantité commandée"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="total_price_bought",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Au moment de l'achat, prend en compte la quantité",
                max_digits=8,
                verbose_name="Coût total de l'article",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="commande.productcategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom du produit"),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Prix d'achat"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="resell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Prix de revente",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Quantité"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="initiator",
            field=models.ForeignKey(
                help_text="Désigne la personne à l'origine de la transaction. Peut-être l'utilisateur lui-même, par exemple lors d'une commande, ou bien un administrateur.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Initiateur de la transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix originel de la commande, sans prendre en compte d'éventuels remboursements",
                max_digits=8,
                verbose_name="Prix originel de la commande",
            ),
        ),
        migrations.RunSQL(
            sql=[
                "SET FOREIGN_KEY_CHECKS = 0;",
                "TRUNCATE auth_permission;",
                "SET FOREIGN_KEY_CHECKS = 1;",
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="get_order_email",
            field=models.BooleanField(
                default=True,
                help_text="Désigne si l'utilisateur souhaite recevoir des mails de confirmation de commande",
                verbose_name="Confirmation de commande",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this product is still available to order. Unselect this instead of deleting the product.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sort",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Numéro indiquant l'ordre d'apparition du produit.",
                verbose_name="Trie",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="sort",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Numéro indiquant l'ordre d'apparition de la catégorie.",
                verbose_name="Trie",
            ),
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["sort"]},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["sort"], "verbose_name_plural": "product categories"},
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix d'achat à la boulangerie.",
                max_digits=8,
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="resell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix de revente aux centraliens sur le site.",
                max_digits=8,
                verbose_name="Prix de revente",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="initiator",
            field=models.ForeignKey(
                help_text="Désigne la personne à l'origine de la transaction. Peut être l'utilisateur lui-même, par exemple lors d'une commande, ou bien un administrateur.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Initiateur de la transaction",
            ),
        ),
        migrations.RunPython(
            code=add_all_permissions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_default_group,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=add_existing_users_to_default_group,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="total_price_bought",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Au moment de l'achat. Prend en compte la quantité",
                max_digits=8,
                verbose_name="Coût payé à la boulangerie pour l'article",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="total_price_sold",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Au moment de l'achat. Prend en compte la quantité",
                max_digits=8,
                verbose_name="Coût payé par le client pour l'article",
            ),
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={"ordering": ["-date"], "verbose_name": "Livraison"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"], "verbose_name": "Commande"},
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "verbose_name": "Produit commandé",
                "verbose_name_plural": "Produits commandés",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["sort"], "verbose_name": "Produit"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "Catégorie produit",
                "verbose_name_plural": "Catégories produit",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Utilisateur"},
        ),
        migrations.AlterField(
            model_name="delivery",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, unique=True, verbose_name="Jour"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Permet de désactiver une livraison sans casser les liens d'éventuelles commandes faites pour ce jour",
                verbose_name="Actif",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("NA", "Rien à signaler"),
                    ("NDELIV", "Échec de livraison, mais récupéré à la boulangerie"),
                    ("NBOUGHT", "Échec de récupération à la boulangerie"),
                    ("CANCEL", "Produit annulé"),
                ],
                default="NA",
                help_text="Permet d'identifier si le produit n'a pas été récupéré à la boulangerie, ou a été récupéré mais pas livré à l'utilisateur",
                max_length=7,
                verbose_name="État de livraison du produit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sort",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Numéro indiquant l'ordre d'apparition du produit.",
                verbose_name="Ordre d'apparition",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mise à jour le"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="sort",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Numéro indiquant l'ordre d'apparition de la catégorie.",
                verbose_name="Ordre d'apparition",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Effectuée le"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Créé le"
            ),
        ),
    ]
