# Generated by Django 5.2.10 on 2026-01-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0032_grande_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort'], 'verbose_name': 'Catégorie produit', 'verbose_name_plural': 'Catégories produit'},
        ),
    ]
