# Generated by Django 5.2.11 on 2026-02-15 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def add_all_permissions(apps=None, schema_editor=None):
    from django.contrib.auth.management import create_permissions

    if apps is None:
        from django.apps import apps

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

def update_default_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    DEFAULT_GROUP_NAME = "default"
    permissions = {
        "add": [],
        "view": ["helloassocheckout"],
        "change": [],
        "delete": [],
    }

    default_group, created = Group.objects.get_or_create(name=DEFAULT_GROUP_NAME)
    for type in permissions:
        for model in permissions[type]:
            try:
                permission = Permission.objects.get(codename=f"{type}_{model}")
                default_group.permissions.add(permission)
            except Permission.DoesNotExist:
                print(f"ERROR: {type}_{model} permission does not exist")

def logout_all_users(apps, schema_editor):
    # We fetch the Session model via the app registry
    try:
        Session = apps.get_model('sessions', 'Session')
        Session.objects.all().delete()
    except LookupError:
        # If the sessions app isn't installed, we skip
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0034_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('ORDER', "Paiement d'une commande"), ('REFUND', "Remboursement d'une commande"), ('LYF', 'Rechargement via LYF'), ('POS', 'Rechargement via TPE'), ('CASH', 'Rechargement via Cash'), ('HAC', 'Rechargement via HelloAsso Checkout'), ('OTHER', 'Autre (à préciser !)')], max_length=6),
        ),
        migrations.CreateModel(
            name='HelloAssoCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_intent_id', models.PositiveIntegerField(unique=True, null=True, blank=True)),
                ('order_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('payement_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='en euros', max_digits=5, verbose_name='Somme')),
                ('status', models.CharField(choices=[('INIT', 'Checkout initié'), ('PEND', 'Checkout effectué, en attente de validation du paiement'), ('DONE', 'Paiement valide, autorisé, et effectué'), ('CONT', 'Paiement contesté par la banque'), ('REIM', 'Paiement remboursé'), ('REFU', 'Paiement refusé par la banque'), ('OTHE', 'Paiement dans un état incertain')], default='INIT', max_length=4, verbose_name='État du paiement')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='helloasso_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='commande.helloassocheckout', verbose_name='Rechargement associé'),
        ),
        migrations.RunPython(
            code=add_all_permissions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=update_default_group,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='helloassocheckout',
            options={'ordering': ['-created_at'], 'verbose_name': 'HelloAsso Checkout'},
        ),
        migrations.RunPython(logout_all_users),
    ]
