# Generated by Django 5.2.11 on 2026-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0035_alter_transaction_type_helloassocheckout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.CharField(default='', help_text="Désigne la chambre de l'utilisateur. Permet de préremplir la chambre de livraison lors d'une commande", max_length=10, verbose_name='Chambre'),
        ),
    ]
