# Generated by Django 5.2.12 on 2026-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0036_alter_user_phone_alter_user_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login'], 'verbose_name': 'Utilisateur'},
        ),
        migrations.AddField(
            model_name='product',
            name='tranchable',
            field=models.BooleanField(default=False, verbose_name='Peut être tranché'),
        ),
    ]
