# Generated by Django 5.2.17 on 2026-08-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0036_alter_user_phone_alter_user_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login'], 'verbose_name': 'Utilisateur'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
