"""
Django settings for paingouin project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from django.templatetags.static import static
from pathlib import Path
import os

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from email.utils import formataddr

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=5sf8@fhdxzr8(c!%-5xx1!5x6x07$%vc^0rr&$4ljgh&v5!w%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['paingouindev.rezoleo.fr', 'www.paingouindev.rezoleo.fr', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'widget_tweaks',
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'tailwind',
    'django_yubin',
    'django_mjml_template',
    'theme',
    "commande",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'paingouin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'paingouin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
       'NAME': 'dbdjango',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'myuser',
        'PASSWORD': 'monpassword',
        'OPTIONS':{
        "init_command": "SET foreign_key_checks = 0;",
        }
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'CET'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

COMPRESS_ROOT = 'paingouin/static/'

COMPRESS_ENABLED = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'commande.Utilisateur'

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = 'login'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')

EMAIL_BACKEND = 'django_yubin.backends.QueuedEmailBackend'
MAILER_USE_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = 'ssl0.ovh.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = formataddr(("L'équipe Pain'Gouin", 'contact@ic-art.fr'))
EMAIL_HOST_PASSWORD = 'Demarchage'

UNFOLD = {
    "SITE_TITLE":"Panel administrateur de Pain'Gouin",
    "SITE_HEADER":"Panel administrateur de Pain'Gouin",
    "SITE_LOGO": {
        "light": lambda request: static("logo/logo.webp"),  # light mode
        "dark": lambda request: static("logo/logo.webp"),  # dark mode
    },
    "SITE_ICON": {
        "light": lambda request: static("logo/logo.webp"),  # light mode
        "dark": lambda request: static("logo/logo.webp"),  # dark mode
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "96x96",
            "type": "image/png",
            "href": lambda request: static("favicon/favicon-96x96.png"),
        },
        {
            "rel": "icon",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon/favicon.svg"),
        },
        {
            "rel": "apple-touch-icon",
            "sizes": "180x180",
            "href": lambda request: static("favicon/apple-touch-icon.png"),
        },
        {
            "rel": "manifest",
            "href": lambda request: static("favicon/site.webmanifest"),
        },
    ],
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Accueil"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Utilisateurs"),
                        "icon": "person",
                        "link": reverse_lazy("admin:commande_utilisateur_changelist"),
                    },
                ],
            },
            {
                "title": _("Commande"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Gestion des catégories"),
                        "icon": "mist",
                        "link": reverse_lazy("admin:commande_categorieproduit_changelist"),
                    },
                    {
                        "title": _("Gestion des articles"),
                        "icon": "bakery_dining",
                        "link": reverse_lazy("admin:commande_produit_changelist"),
                    },
                    {
                        "title": _("Gestion des livraisons"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:commande_livraison_changelist"),
                    },
                    {
                        "title": _("Gestion des commandes"),
                        "icon": "mouse",
                        "link": reverse_lazy("admin:commande_commande_changelist"),
                    },
                    {
                        "title": _("Modification d'une commande"),
                        "icon": "contract_edit",
                        "link": reverse_lazy("admin:modification_commande"),
                    },
                ],
            },
            {
                "title": _("Trésorerie"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Gestion des soldes"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:solde"),
                    },
                    {
                        "title": _("Export d'une livraison vers Excel"),
                        "icon": "table",
                        "link": reverse_lazy("admin:tableur"),
                    },
                ],
            },
        ],
    },
    "THEME": "dark",
    "SHOW_HISTORY": False,
}

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}

CELERY_BROKER_URL = 'amqp://paingouin:xGmyRq8J5CSUT0fgD3m9iGgVs@localhost:5672/paingouinvhost'
