"""
Django settings for paingouin project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.templatetags.static import static
from pathlib import Path
import os

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from email.utils import formataddr
from datetime import time
from import_export.formats.base_formats import XLSX, CSV, ODS

DELIVERY_CUTOFF_TIME = time(6, 30)

GIT_COMMIT = 'Develop'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=5sf8@fhdxzr8(c!%-5xx1!5x6x07$%vc^0rr&$4ljgh&v5!w%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Admins will reveive an email everytime a servererror occurs
ADMINS = [("Example", "example@example.com")]
SERVER_EMAIL = "paingouin@rezoleo.fr"
ALLOWED_HOSTS = ["paingouindev.rezoleo.fr", "www.paingouindev.rezoleo.fr", "127.0.0.1"]

# Allowed verified genuine user emails
VERIFIED_USER_EMAIL_DOMAINS = set(["centrale.centralelille.fr"])

# Application definition

INSTALLED_APPS = [
    "widget_tweaks",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "tailwind",
    "django_yubin",
    "django_mjml_template",
    "crispy_forms",
    "imagekit",
    "import_export",
    "theme",
    "commande",
]
if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "paingouin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "paingouin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "paingouin",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "USER": "root",
        "PASSWORD": "mysql",
        "OPTIONS": {
            "init_command": "SET foreign_key_checks = 0;",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "assets")

COMPRESS_ROOT = "paingouin/static/"

COMPRESS_ENABLED = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]

STATIC_URL = "static/"

AUTH_USER_MODEL = "commande.User"

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "login"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media").replace("\\", "/")

EMAIL_BACKEND = "django_yubin.backends.QueuedEmailBackend"
MAILER_USE_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_HOST = "localhost"
EMAIL_PORT = 1025
EMAIL_HOST_USER = formataddr(("L'équipe Pain'Gouin", "paingouin@rezoleo.fr"))
EMAIL_HOST_PASSWORD = None

UNFOLD = {
    "SITE_TITLE": "Panel administrateur de Pain'Gouin",
    "SITE_HEADER": "Panel administrateur de Pain'Gouin",
    "SITE_LOGO": {
        "light": lambda request: static("logo/logo.webp"),  # light mode
        "dark": lambda request: static("logo/logo.webp"),  # dark mode
    },
    "SITE_ICON": {
        "light": lambda request: static("logo/logo.webp"),  # light mode
        "dark": lambda request: static("logo/logo.webp"),  # dark mode
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "96x96",
            "type": "image/png",
            "href": lambda request: static("favicon/favicon-96x96.png"),
        },
        {
            "rel": "icon",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon/favicon.svg"),
        },
        {
            "rel": "apple-touch-icon",
            "sizes": "180x180",
            "href": lambda request: static("favicon/apple-touch-icon.png"),
        },
        {
            "rel": "manifest",
            "href": lambda request: static("favicon/site.webmanifest"),
        },
    ],
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Administratif"),
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Utilisateurs"),
                        "icon": "person",
                        "link": reverse_lazy("admin:commande_user_changelist"),
                    },
                    {
                        "title": _("Transactions"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:commande_transaction_changelist"),
                    },
                    {
                        "title": _("Logs"),
                        "icon": "contract",
                        "link": reverse_lazy("admin:admin_logentry_changelist"),
                    },
                ],
            },
            {
                "title": _("Gestion des commandes"),
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Dates de livraison"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:commande_delivery_changelist"),
                    },
                    {
                        "title": _("Commandes"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:commande_order_changelist"),
                    },
                    {
                        "title": _("Produits commandés"),
                        "icon": "package_2",
                        "link": reverse_lazy("admin:commande_orderproduct_changelist"),
                    },
                    {
                        "title": _("Modification d'une commande"),
                        "icon": "contract_edit",
                        "link": reverse_lazy("livreur"),
                    },
                ],
            },
            {
                "title": _("Gestion du site"),
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Produits"),
                        "icon": "bakery_dining",
                        "link": reverse_lazy("admin:commande_product_changelist"),
                    },
                    {
                        "title": _("Catégories"),
                        "icon": "mist",
                        "link": reverse_lazy(
                            "admin:commande_productcategory_changelist"
                        ),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "page": "users",
            "models": [
                "commande.user",
            ],
            "items": [
                {
                    "title": _("Utilisateurs"),
                    "link": reverse_lazy("admin:commande_user_changelist"),
                    "active": lambda request: request.path
                    == reverse_lazy("admin:commande_user_changelist")
                    and "status__exact" not in request.GET,
                },
                {
                    "title": _("Précréation d'un utilisateur"),
                    "link": reverse_lazy("admin:precreation_utilisateur"),
                },
                {
                    "title": _("Précréation de plusieurs utilisateurs"),
                    "link": reverse_lazy("admin:precreation_utilisateurs"),
                },
            ],
        },
    ],
    "THEME": "dark",
    "SHOW_HISTORY": False,
}

# https://docs.djangoproject.com/en/5.1/ref/settings/#date-input-formats
DATE_INPUT_FORMATS = [
    "%d.%m.%Y",  # Custom input
    "%Y-%m-%d",  # '2006-10-25'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y",  # '10/25/06'
    "%b %d %Y",  # 'Oct 25 2006'
    "%b %d, %Y",  # 'Oct 25, 2006'
    "%d %b %Y",  # '25 Oct 2006'
    "%d %b, %Y",  # '25 Oct, 2006'
    "%B %d %Y",  # 'October 25 2006'
    "%B %d, %Y",  # 'October 25, 2006'
    "%d %B %Y",  # '25 October 2006'
    "%d %B, %Y",  # '25 October, 2006'
]

# https://docs.djangoproject.com/en/5.1/ref/settings/#datetime-input-formats
DATETIME_INPUT_FORMATS = [
    "%d.%m.%Y %H:%M:%S",  # Custom input
    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
    "%Y-%m-%d %H:%M:%S.%f",  # '2006-10-25 14:30:59.000200'
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
    "%m/%d/%Y %H:%M:%S.%f",  # '10/25/2006 14:30:59.000200'
    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
    "%m/%d/%y %H:%M:%S.%f",  # '10/25/06 14:30:59.000200'
    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

CELERY_BROKER_URL = (
    "amqp://paingouin:xGmyRq8J5CSUT0fgD3m9iGgVs@localhost:5672/paingouinvhost"
)

CRISPY_TEMPLATE_PACK = "unfold_crispy"

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

# For django-import-export
IMPORT_EXPORT_FORMATS = [CSV, ODS, XLSX]
