"""
Django settings for paingouin project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import time
from decimal import Decimal
from email.utils import formataddr
from pathlib import Path

import environ  # using django-environ for env variables: https://django-environ.readthedocs.io/
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from import_export.formats.base_formats import CSV, ODS, XLSX

env = environ.Env()

# Set the project base directory
BASE_DIR = Path(__file__).parent.parent

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / ".env")

DEBUG = env("DEBUG", bool, default=False)

DELIVERY_CUTOFF_TIME = time(6, 30)

GIT_COMMIT = env("GIT_COMMIT_SHA", default="na")[:7]

PROD = env("PROD", default=False)

SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-=5sf8@fhdxzr8(c!%-5xx1!5x6x07$%vc^0rr&$4ljgh&v5!w%",
)

MINIMAL = env(
    "MINIMAL", bool, default=True
)  # Wether only minimal dependencies for prod were included

ALLOWED_HOSTS = env(
    "DJANGO_ALLOWED_HOSTS", list, ["paingouin.rezoleo.fr", "www.paingouin.rezoleo.fr"]
)

CSRF_TRUSTED_ORIGINS = env(
    "DJANGO_CSRF_TRUSTED_ORIGINS", list, ["https://paingouin.rezoleo.fr"]
)

# HTTPS Enforcing
if env("ENFORCE_HTTPS", bool, default=True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Admins will reveive an email everytime a server error occurs
ADMINS = [("vale", "margerite.tonnere@gmail.com")]

# Allowed verified genuine user emails
VERIFIED_USER_EMAIL_DOMAINS = {"centrale.centralelille.fr"}

MAX_TOPUP_AMOUNT = Decimal(99)
MAX_BALANCE_ALLOWED = Decimal(150)
LOW_BALANCE_WARNING_THRESHOLD = Decimal(2)

# Application definition

INSTALLED_APPS = [
    "widget_tweaks",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "tailwind",
    "django_yubin",
    "django_mjml_template",
    "crispy_forms",
    "imagekit",
    "import_export",
    "theme",
    "commande",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG and not MINIMAL:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += [
        "django_browser_reload",
        "django_watchfiles",
    ]
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "paingouin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                "commande.utils.context_processors.export_debug_status_data",
            ],
        },
    },
]

WSGI_APPLICATION = "paingouin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DATABASE_NAME", default="paingouin"),
        "HOST": env("DATABASE_HOST", default="mysql.rezoleo.fr"),
        "PORT": env("DATABASE_PORT", default="3306"),
        "USER": env("DATABASE_USERNAME", default="paingouin"),
        "PASSWORD": env("DATABASE_PASSWORD", default=""),
        "OPTIONS": {
            "init_command": "SET foreign_key_checks = 0;",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "assets"

COMPRESS_ROOT = "paingouin/static/"

COMPRESS_ENABLED = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]

AUTH_USER_MODEL = "commande.User"

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "login"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

EMAIL_BACKEND = "django_yubin.backends.QueuedEmailBackend"
MAILER_USE_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = env("EMAIL_USE_TLS", bool, default=True)
EMAIL_USE_SSL = env("EMAIL_USE_SSL", bool, default=True)
EMAIL_HOST = env("EMAIL_HOST", default="smtp.rezoleo.fr")
EMAIL_PORT = env("EMAIL_PORT", int, 1025)
EMAIL_HOST_USER = formataddr(
    (
        "L'équipe Pain'Gouin",
        env("EMAIL_HOST_USER", default="noreply@paingouin.rezoleo.fr"),
    )
)
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
SERVER_EMAIL = "admin." + env(
    "EMAIL_HOST_USER", default="noreply@paingouin.rezoleo.fr"
)  # Used for admin emails

UNFOLD = {
    "SITE_TITLE": "Panel administrateur de Pain'Gouin",
    "SITE_HEADER": "Panel administrateur de Pain'Gouin",
    "SITE_LOGO": {
        "light": lambda request: static("logo/logo.webp"),  # light mode
        "dark": lambda request: static("logo/logo.webp"),  # dark mode
    },
    "SITE_ICON": {
        "light": lambda request: static("logo/logo.webp"),  # light mode
        "dark": lambda request: static("logo/logo.webp"),  # dark mode
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "96x96",
            "type": "image/png",
            "href": lambda request: static("favicon/favicon-96x96.png"),
        },
        {
            "rel": "icon",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon/favicon.svg"),
        },
        {
            "rel": "apple-touch-icon",
            "sizes": "180x180",
            "href": lambda request: static("favicon/apple-touch-icon.png"),
        },
        {
            "rel": "manifest",
            "href": lambda request: static("favicon/site.webmanifest"),
        },
    ],
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Administratif"),
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Utilisateurs"),
                        "icon": "person",
                        "link": reverse_lazy("admin:commande_user_changelist"),
                    },
                    {
                        "title": _("Transactions"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:commande_transaction_changelist"),
                    },
                    {
                        "title": _("HelloAsso Checkout"),
                        "icon": "credit_card",
                        "link": reverse_lazy(
                            "admin:commande_helloassocheckout_changelist"
                        ),
                    },
                    {
                        "title": _("Logs"),
                        "icon": "contract",
                        "link": reverse_lazy("admin:admin_logentry_changelist"),
                    },
                ],
            },
            {
                "title": _("Gestion des commandes"),
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Dates de livraison"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:commande_delivery_changelist"),
                    },
                    {
                        "title": _("Commandes"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:commande_order_changelist"),
                    },
                    {
                        "title": _("Produits commandés"),
                        "icon": "package_2",
                        "link": reverse_lazy("admin:commande_orderproduct_changelist"),
                    },
                    {
                        "title": _("Modification d'une commande"),
                        "icon": "contract_edit",
                        "link": reverse_lazy("livreur"),
                    },
                ],
            },
            {
                "title": _("Gestion du site"),
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Produits"),
                        "icon": "bakery_dining",
                        "link": reverse_lazy("admin:commande_product_changelist"),
                    },
                    {
                        "title": _("Catégories"),
                        "icon": "mist",
                        "link": reverse_lazy(
                            "admin:commande_productcategory_changelist"
                        ),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "page": "users",
            "models": [
                "commande.user",
            ],
            "items": [
                {
                    "title": _("Utilisateurs"),
                    "link": reverse_lazy("admin:commande_user_changelist"),
                    "active": lambda request: (
                        request.path == reverse_lazy("admin:commande_user_changelist")
                        and "status__exact" not in request.GET
                    ),
                },
                {
                    "title": _("Précréation d'un utilisateur"),
                    "link": reverse_lazy("admin:precreation_utilisateur"),
                },
                {
                    "title": _("Précréation de plusieurs utilisateurs"),
                    "link": reverse_lazy("admin:precreation_utilisateurs"),
                },
            ],
        },
    ],
    "SHOW_HISTORY": False,
    # To remove the default "view site" button, and add it back just after, to not make it open a new tab
    "SITE_URL": None,
    "ACCOUNT": {
        "navigation": [
            {
                "title": _("Voir le site"),
                "link": reverse_lazy("index"),
            }
        ],
    },
}
if not PROD:
    # To add visual styling to destingish dev from prod site
    UNFOLD["STYLES"] = [lambda request: static("css/unfold_dev.css")]

# https://docs.djangoproject.com/en/5.2/ref/settings/#date-input-formats
DATE_INPUT_FORMATS = [
    "%d.%m.%Y",  # Custom input
    "%Y-%m-%d",  # '2006-10-25'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y",  # '10/25/06'
    "%b %d %Y",  # 'Oct 25 2006'
    "%b %d, %Y",  # 'Oct 25, 2006'
    "%d %b %Y",  # '25 Oct 2006'
    "%d %b, %Y",  # '25 Oct, 2006'
    "%B %d %Y",  # 'October 25 2006'
    "%B %d, %Y",  # 'October 25, 2006'
    "%d %B %Y",  # '25 October 2006'
    "%d %B, %Y",  # '25 October, 2006'
]

# https://docs.djangoproject.com/en/5.2/ref/settings/#datetime-input-formats
DATETIME_INPUT_FORMATS = [
    "%d.%m.%Y %H:%M:%S",  # Custom input
    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
    "%Y-%m-%d %H:%M:%S.%f",  # '2006-10-25 14:30:59.000200'
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
    "%m/%d/%Y %H:%M:%S.%f",  # '10/25/2006 14:30:59.000200'
    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
    "%m/%d/%y %H:%M:%S.%f",  # '10/25/06 14:30:59.000200'
    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

CELERY_BROKER_URL = (
    "amqp://"
    + env("RABBITMQ_USER", str, "paingouin")
    + ":"
    + env("RABBITMQ_PASS", str, "xGmyRq8J5CSUT0fgD3m9iGgVs")
    + "@"
    + env("RABBITMQ_HOST", str, "rabbitmq")
    + ":"
    + env("RABBITMQ_PORT", str, "5672")
    + "/"
    + env("RABBITMQ_VHOST", str, "paingouinvhost")
)

CRISPY_TEMPLATE_PACK = "unfold_crispy"

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

# For django-import-export
IMPORT_EXPORT_FORMATS = [CSV, ODS, XLSX]

# Used to cache oAuth token from HelloAsso API
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}

if PROD:
    HELLOASSO_TOKEN_URL = "https://api.helloasso.com/oauth2/token"  # noqa: S105
    HELLOASSO_API_URL = "https://api.helloasso.com/v5"
else:
    HELLOASSO_TOKEN_URL = "https://api.helloasso-sandbox.com/oauth2/token"  # noqa: S105
    HELLOASSO_API_URL = "https://api.helloasso-sandbox.com/v5"
HELLOASSO_CLIENT_ID = env("HELLOASSO_CLIENT_ID", str, "")
HELLOASSO_CLIENT_SECRET = env("HELLOASSO_CLIENT_SECRET", str, "")
HELLOASSO_ORG_SLUG = env("HELLOASSO_ORG_SLUG", str, "pain-gouin")
